Simplify model configs
EleutherAI/weak-to-strong pull request #12
Opened 2024-02-12 14:39 UTC by ojh31

In anticipation for lots of new models when investigating scaling laws, I have taken the opportunity to simplify the model configs:

- Migrated config dicts to yaml
- Added memory requirements to model config
- Set model_parallel, gradient_checkpointing programatically based on size
- Moved default minibatch size to model config class
- Added docstring to model config class

2024-02-12 17:09 UTC, AlexTMallen commented
I like this change! One thing I'll note is that memory requirements vary depending on the context length of the dataset, so we will need to do some nudging of that depending on dataset

2024-02-12 17:46 UTC, AlexTMallen requested changes
Looks good overall! Just minor requests:

1. Switch from "bf16" and "fp32" to using the "torch_dtype" arg exclusively.
2. Tweak the docstring as mentioned
3. Account for the varying memory footprint based on context length size (and LoRA, though I wouldn't spend too much time on this since we don't really intend to use full finetuning). Accounting for context length might involve dynamically modifying a ModelConfig object before instantiating a model based on the passed max context length argument to train_simple, and the relationship between context length and memory should be proportional.

2024-02-12 17:46 UTC, AlexTMallen commented on weak_to_strong/config.py
> +            The list of LORA modules. Defaults to None.
Thanks for adding the docstring! One other detail that should be added here is that LoRA will be used IFF `lora_modules` is not None

2024-02-12 17:46 UTC, AlexTMallen commented on weak_to_strong/config.py
> +            Custom keyword arguments. Defaults to None.
These kwargs are passed to the model.from_pretrained call

2024-02-12 17:46 UTC, AlexTMallen commented on weak_to_strong/config.py
> +            Whether to use model parallelism. Defaults to None.
Model parallelism uses accelerate's automatic model sharding, while if model-parallel is false and you're using multiple GPUs, it uses data parallelism

2024-02-12 17:46 UTC, AlexTMallen commented on weak_to_strong/config.py
> +    MODEL_PARALLEL_FACTOR = 2
It would be good to also include a factor for max context length.

I'm wondering why this factor is so large--what does the `memory` parameter mean?

2024-02-12 17:46 UTC, AlexTMallen commented on weak_to_strong/config.py
> +        if not torch.cuda.is_bf16_supported() and custom_kwargs.get("bf16"):
I think we can get rid of this block because the first block is equivalent with appropriate yaml parameters (and modify the yamls accordingly). See [this PR](https://github.com/openai/weak-to-strong/commit/c01b150515581cb4f18bb59cadd677cecc207c14)

2024-02-12 17:46 UTC, AlexTMallen commented on weak_to_strong/config.py
> +        if not torch.cuda.is_bf16_supported() and custom_kwargs.get("bf16"):
We should probably be using bf16 for more (all?) models since we're using LoRA

2024-02-12 18:39 UTC, ojh31 commented on weak_to_strong/config.py
> +    MODEL_PARALLEL_FACTOR = 2
You think 2 is too large? I set the memory values here by looking at pytorch_model.bin sizes on huggingface. Ultimately though it's an arbitrary, configurable parameter which affects whether we use model parallelism, gradient checkpointing and bfloat16 by default.

2024-02-12 18:53 UTC, ojh31 commented on weak_to_strong/config.py
> +        if not torch.cuda.is_bf16_supported() and custom_kwargs.get("bf16"):
> I think we can get rid of this block because the first block is equivalent with appropriate yaml parameters (and modify the yamls accordingly). See [this PR](https://github.com/openai/weak-to-strong/commit/c01b150515581cb4f18bb59cadd677cecc207c14)

In that case, this is much simpler, thank you!

2024-02-16 17:55 UTC, AlexTMallen approved these changes

2024-02-16 17:55 UTC, merged